defaults:
  - _common/pipeline@_here_
  - _common/source_parquet@_here_
  - _common/materialize_interleave@_here_
  - _self_

name: infore2

convert:
  input:
    parquet_dir: /capstor/store/cscs/swissai/infra01/audio-datasets/raw/doof-ferb___infore2_audiobooks/data
    parquet_glob: train-*.parquet
  output:
    shar_dir: /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/infore2_audiobooks_train_fixed_ids_v4
  metadata:
    text_column: transcription
    id_column: audio.path
    language: vi
    input_clip_id_parser: trailing_number_basename

materialize:
  interleave:
    cache_dir: /capstor/store/cscs/swissai/infra01/audio-datasets/tokenized/cooldown/interleave_cache/infore2_v2
    output_dir: /capstor/store/cscs/swissai/infra01/audio-datasets/tokenized/cooldown/infore2_interleaved
