# ------------------------------------------------------------------
# Input
# ------------------------------------------------------------------
shar_dir:
  - /iopsstor/scratch/cscs/arsaikia/librilight/shar_output/node_0
  - /iopsstor/scratch/cscs/arsaikia/librilight/shar_output/node_1
  - /iopsstor/scratch/cscs/arsaikia/librilight/shar_output/node_2
  - /iopsstor/scratch/cscs/arsaikia/librilight/shar_output/node_3        
shar_index_filename: shar_index.json  
type: audio_only              

# ------------------------------------------------------------------
# Output
# ------------------------------------------------------------------
output_dir: "/iopsstor/scratch/cscs/arsaikia/librilight/cutsets/checkpoints"
output_dir_data: "/iopsstor/scratch/cscs/arsaikia/librilight/cutsets"
output_format: "cuts_only"

# ------------------------------------------------------------------
# Audio filtering & resampling
# ------------------------------------------------------------------
target_sample_rate: 16000
min_sample_rate: 8000
min_duration:                            
max_duration:                            

# ------------------------------------------------------------------
# ASR
# ------------------------------------------------------------------
nvidia_model: "nvidia/parakeet-tdt-0.6b-v3"
NVIDIA_LANGUAGES: [] #[bg, hr, cs, da, nl, en, et, fi, fr, de, el, hu, it, lv, lt, mt, pl, pt, ro, sk, sl, es, sv, ru, uk]
whisper_model_id: "openai/whisper-large-v3"
transcribe: true                 
cache_dir: /iopsstor/scratch/cscs/arsaikia/.cache                            
# language_detection_samples: 5            # Number of samples to decide the language of a shard

# ------------------------------------------------------------------
# Text tokenization
# ------------------------------------------------------------------
calculate_cer: false

# ------------------------------------------------------------------
# Text tokenization
# ------------------------------------------------------------------
include_text_tokens: true
use_transcription: true
text_tokenizer_path: "/capstor/store/cscs/swissai/infra01/MLLM/tokenizer/apertus_emu3.5_wavtok/tokenizer.json"

# ------------------------------------------------------------------
# DataLoader & Sampler
# ------------------------------------------------------------------
num_workers: 4
prefetch_factor: 4
dataloader_timeout: 300
max_batch_duration: 500.0
max_batch_cuts: 32                        
num_buckets: 20
bucket_buffer_size: 20000
sampler_shuffle: false
sampler_seed: 42
# quadratic_duration:                    

# ------------------------------------------------------------------
# Checkpointing & Error handling
# ------------------------------------------------------------------
resume: true
checkpoint_interval_batches: 500
max_consecutive_errors: 50

# ------------------------------------------------------------------
# W&B Logging
# ------------------------------------------------------------------
wandb:
  enabled: true
  project: "audio-preprocessing"
  entity:                                
  name: "librilight"                               
  tags: []
  log_interval_seconds: 10.0
