# CommonVoice zh-CN (other split) — audio-only tokenization.
defaults:
  - ../_base_
  - _self_

output_name: commonvoice_zh-CN_other

# Pre-built Shar directory
shar_dir: /iopsstor/scratch/cscs/xyixuan/audio-datasets/shar/commonvoice_zh-CN_other_shar

min_duration: 4.0
max_duration: 500.0
max_batch_duration: 1000.0
