# AISHELL-1 + AISHELL-3 train — audio-text direct tokenization.
dataset_name: aishell
output_name: aishell_1_3_direct

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell1_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell3_train
