# AISHELL 1+3 direct — audio-text tokenization.
# ~220h, Mandarin, standalone utterances.

dataset_name: aishell
output_name: aishell_1_3

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell1_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell3_train

num_buckets: 20
