# AISHELL-4 interleaved — audio-text tokenization.
# ~100h, Mandarin meeting recordings, multi-speaker conversations.

dataset_name: aishell4
output_name: aishell4_interleave

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell4_train_L
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell4_train_M
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/aishell/aishell4_train_S

num_buckets: 20
