# CommonVoice 48-language stage_2 (train) — audio-text direct tokenization.
defaults:
  - ../_base_
  - _self_

dataset_name: commonvoice
output_name: commonvoice_48lang_S2
clip_id_parser: generic

# Pre-built Shar directories (one per language)
shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ar_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/be_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/bg_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ca_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/cs_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/cy_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/da_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/de_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/el_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/en_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/eo_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/es_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/et_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/eu_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/fa_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/fi_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/fr_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ga-IE_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/gl_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/hu_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/hy-AM_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/id_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/is_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/it_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ja_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ka_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ko_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/lt_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/lv_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/mk_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/mt_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/nb-NO_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/nl_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/nn-NO_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/pl_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/pt_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/rm-sursilv_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ro_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/ru_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/sv-SE_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/th_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/tr_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/uk_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/vi_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/yue_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/zh-CN_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/zh-HK_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/commonvoice/zh-TW_train

min_duration: 3.0
max_batch_duration: 1500.0
