# CommonVoice ca/de/en/fr/it/pt/zh-CN train — audio-text tokenization.
dataset_name: commonvoice
output_name: commonvoice_ca_de_en_fr_it_pt_zh-CN_train
clip_id_parser: generic

# Pre-built Shar directories
shar_dir:
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_ca_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_de_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_en_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_fr_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_it_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_pt_train_shar
  - /iopsstor/scratch/cscs/xyixuan/audio-datasets/audio_text_as_repetition_shar/commonvoice_zh-CN_train_shar

min_duration: 2.0
max_batch_duration: 1500.0
num_workers: 4
checkpoint_interval_batches: 500
