# EuroSpeech permissive languages — audio-text direct tokenization.
# Italy (CC BY 4.0), UK (OGL v3.0), Bulgaria (CC BY 2.5), France (Licence Ouverte), Norway (NLOD 2.0)

dataset_name: eurospeech_permissive
output_name: eurospeech_permissive_direct

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/eurospeech/italy_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/eurospeech/uk_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/eurospeech/bulgaria_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/eurospeech/france_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/eurospeech/norway_train
