# GigaSpeech XL — audio-text direct tokenization.
# ~8.3M segments, ~10Kh English speech with normalized text.

dataset_name: gigaspeech
output_name: gigaspeech

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/gigaspeech/node_00
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/gigaspeech/node_01
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/gigaspeech/node_02
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/gigaspeech/node_03

num_buckets: 80
num_workers: 16
prefetch_factor: 4
