# Granary YODAS Translate — audio-text direct translate tokenization.
# Same audio as granary_yodas_ast, with English translation as supervision.

dataset_name: granary_yodas_translate
output_name: granary_yodas_translate

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/translate/granary_yodas_ast

num_buckets: 80
