# Granary YODAS interleaved — audio-text tokenization.
# ~192Kh, 23 languages, 92 shards.

dataset_name: granary_yodas_interleave
output_name: granary_yodas_interleave

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/bg000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/cs000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/da000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/de000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/de100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/de101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/de102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/el000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en001
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en002
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en003
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en004
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en005
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en006
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en007
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en103
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en104
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en105
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en106
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en107
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en108
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en109
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en110
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en111
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en112
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en113
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en114
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en115
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en116
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en117
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en118
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en119
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en120
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en121
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en122
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en123
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en124
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en125
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en126
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en127
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en128
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/en129
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es103
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es104
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es105
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es106
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es107
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/es108
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/et000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fi000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fr000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fr100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fr101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fr102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/fr103
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/hr000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/hu000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/it000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/it100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/it101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/lt000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/lv000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/nl000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/nl100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pl000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pt000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pt100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pt101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pt102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/pt103
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ro000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru001
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru100
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru101
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru102
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru103
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru104
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru105
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/ru106
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/sk000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/sv000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/uk000
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_yodas_interleave/uk100

num_buckets: 80
