# Granary YTC AST direct — audio-text tokenization.
# ~5.1Kh, 22 languages (no English), English translation.

dataset_name: granary_ytc_ast
output_name: granary_ytc_ast

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/bg
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/cs
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/da
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/de
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/el
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/es
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/et
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/fi
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/fr
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/hr
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/hu
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/it
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/lt
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/lv
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/nl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/pl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/pt
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/ro
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/sk
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/sl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/sv
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/granary_ytc_ast/uk

num_buckets: 80
