# LegCo speech train split — audio-text interleaved tokenization.

dataset_name: legco_speech
output_name: legco_speech_train_interleaved
clip_id_parser: legco

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/legco_speech_train/node_00
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/legco_speech_train/node_01
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/legco_speech_train/node_02
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/legco_speech_train/node_03

min_duration: 0.1
