# LibriHeavy large interleaved — audio-text tokenization.
# ~45.8Kh, English audiobooks, ~67 clips/chapter.

dataset_name: libriheavy_large
output_name: libriheavy_large_interleave

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/libriheavy_large

num_buckets: 80
