# MLS (Multilingual LibriSpeech) 8 languages — audio-text interleaved tokenization.
defaults:
  - ../_base_
  - _self_

dataset_name: mls
output_name: mls_8lang_interleaved

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_dutch_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_english_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_french_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_german_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_italian_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_polish_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_portuguese_train
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/mls/mls_spanish_train

num_workers: 40
