# Omnilingual ASR — audio-text direct transcribe tokenization.
# 184K cuts, 2.3Kh, 348 languages.

dataset_name: omnilingual_asr
output_name: omnilingual_asr

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/omnilingual_asr

num_buckets: 40
