# Parlament Parla v3 direct — audio-text tokenization.
# ~741h, Catalan parliamentary speech.

dataset_name: parlament_parla
output_name: parlament_parla

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/parlament_parla

num_buckets: 80
