# People's Speech train (clean + dirty) — audio-text interleaved tokenization.

dataset_name: peoples_speech
output_name: peoples_speech_train_interleaved

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/peoples_speech_train_v2

min_duration: 1.0
