# SPC-R Segmented interleaved — audio-text tokenization.
# ~482h, Swiss-German parliamentary speech.

dataset_name: spc_r
output_name: spc_r_interleave

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/spc_r_segmented

num_buckets: 20
