# Granary VoxPopuli AST direct — audio-text tokenization.
# ~335Kh, 22 languages (no English), English translation as supervision.

dataset_name: voxpopuli_ast
output_name: voxpopuli_ast

shar_dir:
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/bg
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/cs
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/da
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/de
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/el
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/es
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/et
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/fi
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/fr
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/hr
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/hu
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/it
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/lt
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/lv
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/mt
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/nl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/pl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/pt
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/ro
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/sk
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/sl
  - /capstor/store/cscs/swissai/infra01/audio-datasets/SHAR/stage_2/voxpopuli_ast/sv

num_buckets: 80
